/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmBarang.java
 *
 * 
 */
package Forms;
import cls.ClassDB;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author NoName
 */

public final class FrmFile extends javax.swing.JInternalFrame {
    cls.ClassDB koneksi = new cls.ClassDB();

    private Object tblbarang;
    Map<String, Object> param = new HashMap<String, Object>();
    private DefaultTableModel model;
   Connection conn;
    Statement stat;
    ResultSet hasil;

    public FrmFile() {
        initComponents();
        BersihText();
        aktifText(false);
        model=new DefaultTableModel();
        table.setModel(model);
        model.addColumn("No. Investaris");
        model.addColumn("Jenis Investaris");
        model.addColumn("Nama Investaris");
        model.addColumn("Tahun Perolehan");
        model.addColumn("Bagian");
        model.addColumn("Seksi");
        model.addColumn("Ruang");
        model.addColumn("Kondisi");
        model.addColumn("Keterangan");
        loadData();
        }


public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tblbarang";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Object[] a=new Object[9];
                a[0]=r.getString("nomor");
                a[1]=r.getString("jenis");
                a[2]=r.getString("nama");
                a[3]=r.getString("tahun");
                a[4]=r.getString("bagian");
                a[5]=r.getString("seksi");
                a[6]=r.getString("ruang");
                a[7]=r.getString("kondisi");
                a[8]=r.getString("keterangan");
                model.addRow(a);
            }
            r.close();
            s.close();
            ShowData();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
    }

public void mouseClicked(MouseEvent e) {
      ShowData();
   }

public void ShowData() {

    int i=table.getSelectedRow();

        if(i==-1)
        {
            return;
        }
        String nomor=(String) model.getValueAt(i, 0);
        TxtNomor.setText(nomor);
        String jenis=(String) model.getValueAt(i, 1);
        cbojenis.setSelectedItem(jenis);
        String nama=(String) model.getValueAt(i, 2);
        cbojenis.setSelectedItem(nama);
        String tahun=(String) model.getValueAt(i, 3);
        TxtNama.setText(tahun);
        String bagian=(String) model.getValueAt(i, 4);
        cboSeksi.setSelectedItem(bagian);
        String seksi=(String) model.getValueAt(i, 5);
        cboSeksi.setSelectedItem(seksi);
        String ruang=(String) model.getValueAt(i, 6);
        cboSeksi.setSelectedItem(ruang);
        String kondisi=(String) model.getValueAt(i, 7);
        cbokondisi.setSelectedItem(kondisi);
        String keterangan=(String) model.getValueAt(i, 8);
        TxtKeterangan.setText(keterangan);
}


    private void aktifText(boolean param)
    {
        TxtNomor.setEnabled(param);
        cbojenis.setEnabled(param);
        TxtNama.setEnabled(param);
        TxtTahun.setEnabled(param);
        cboBagian.setEnabled(param);
        cboSeksi.setEnabled(param);
        cboRuang.setEnabled(param);
        cbokondisi.setEnabled(param);
        TxtKeterangan.setEnabled(param);
        btnSimpan.setEnabled(param);
        btnHapus.setEnabled(param);
        btnBatal.setEnabled(param);
        btnCari.setEnabled(param);
    }

    private void BersihText()
    {
        TxtNomor.setText("");
        TxtNama.setText("");
        TxtTahun.setText("");
        TxtKeterangan.setText("");
        btnSimpan.setText("Simpan");
        btnSimpan.setMnemonic('S');
        btnTambah.setText("Tambah");
        btnTambah.setMnemonic('T');
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNomor = new javax.swing.JTextField();
        cboSeksi = new javax.swing.JComboBox();
        cbokondisi = new javax.swing.JComboBox();
        TxtKeterangan = new javax.swing.JTextField();
        cbojenis = new javax.swing.JComboBox();
        btnCari = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtTahun = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboBagian = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cboRuang = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setTitle("Input Data Inventaris");
        setFont(new java.awt.Font("Tahoma", 0, 10));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        table.setFont(new java.awt.Font("Segoe UI Light", 0, 13));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Inventaris", "Jenis Inventaris", "Nama Inventaris", "Tahun Perolehan", "Bagian", "Seksi", "Ruang", "Kondisi", "Keterangan"
            }
        ));
        table.setRowSelectionAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel9.setText("Keterangan");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel8.setText("Kondisi");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel7.setText("Seksi");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Inventaris");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("No. Inventaris");

        TxtNomor.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomorActionPerformed(evt);
            }
        });
        TxtNomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNomorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNomorKeyTyped(evt);
            }
        });

        cboSeksi.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        cboSeksi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSeksiItemStateChanged(evt);
            }
        });
        cboSeksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSeksiActionPerformed(evt);
            }
        });

        cbokondisi.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        cbokondisi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baik", "Buruk" }));
        cbokondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbokondisiActionPerformed(evt);
            }
        });

        TxtKeterangan.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        TxtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKeteranganActionPerformed(evt);
            }
        });

        cbojenis.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cbojenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbojenisItemStateChanged(evt);
            }
        });
        cbojenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbojenisActionPerformed(evt);
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add.png"))); // NOI18N
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setText("Tahun Perolehan");

        TxtNama.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });
        TxtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNamaKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setText("Nama Inventaris");

        TxtTahun.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        TxtTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTahunActionPerformed(evt);
            }
        });
        TxtTahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtTahunKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTahunKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel15.setText("Bagian");

        cboBagian.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        cboBagian.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih -", "Jaringan", "Transaksi Energi Listrik", "Pelayanan & Adm", "Kosong" }));
        cboBagian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBagianItemStateChanged(evt);
            }
        });
        cboBagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBagianActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel16.setText("Ruang");

        cboRuang.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        cboRuang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRuangItemStateChanged(evt);
            }
        });
        cboRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRuangActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel11.setBackground(new java.awt.Color(255, 204, 51));
        jLabel11.setFont(new java.awt.Font("Eurostile", 0, 30));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Entri Data Inventaris");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(601, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        btnTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/New.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/OK.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Trash.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Refresh-32.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Exit.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnTambah)
                .addGap(38, 38, 38)
                .addComponent(btnSimpan)
                .addGap(44, 44, 44)
                .addComponent(btnHapus)
                .addGap(40, 40, 40)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 624, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnTambah)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboRuang, javax.swing.GroupLayout.Alignment.LEADING, 0, 169, Short.MAX_VALUE)
                            .addComponent(cboBagian, javax.swing.GroupLayout.Alignment.LEADING, 0, 169, Short.MAX_VALUE)
                            .addComponent(cbokondisi, javax.swing.GroupLayout.Alignment.LEADING, 0, 169, Short.MAX_VALUE)
                            .addComponent(cbojenis, javax.swing.GroupLayout.Alignment.LEADING, 0, 169, Short.MAX_VALUE)
                            .addComponent(TxtKeterangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(cboSeksi, javax.swing.GroupLayout.Alignment.LEADING, 0, 169, Short.MAX_VALUE)
                            .addComponent(TxtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(TxtNomor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbojenis, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboBagian, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSeksi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbokondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        ShowData();
    }//GEN-LAST:event_tblBarangMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       
    }//GEN-LAST:event_formMouseMoved

    private void TxtNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomorActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (btnTambah.getText()=="Tambah") {
            aktifText(true);
            this.TxtNomor.requestFocusInWindow();
        }
         else if (btnTambah.getText()=="Edit") {
            btnTambah.setText("Edit");
            btnSimpan.setText("Update");
            btnSimpan.setMnemonic('U');
            aktifText(true);
            TxtNomor.setEnabled(false);
            cbojenis.requestFocus();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nomor="", jenis="", nama="", tahun="", bagian="", seksi="", ruang="", kondisi="",keterangan="",sql="";
        nomor=TxtNomor.getText();
        nama=TxtNama.getText();
        keterangan =TxtKeterangan.getText();
    if ((nomor.isEmpty()) | (nama.isEmpty())| (keterangan.isEmpty()))
       {JOptionPane.showMessageDialog(null,"Data Tidak Boleh Kosong, Silahkan Dilengkapi");
        TxtNomor.requestFocus();
    }
else{
        try{
            nomor=TxtNomor.getText();
            jenis=cbojenis.getSelectedItem().toString();
            nama=TxtNama.getText();
            tahun=(TxtTahun.getText());
            bagian=cboBagian.getSelectedItem().toString();
            seksi=cboSeksi.getSelectedItem().toString();
            ruang=cboRuang.getSelectedItem().toString();
            kondisi =cbokondisi.getSelectedItem().toString();
            keterangan =TxtKeterangan.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");

            if (btnSimpan.getText()=="Simpan") {
                sql="Insert into tblbarang values('"+nomor+"','"+jenis+"','"+nama+"', '"+tahun+"', '"+bagian+"', '"+seksi+"', '"+ruang+"', '"+kondisi+"', '"+keterangan+"')";
                Statement st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Sudah Disimpan","SIMPAN",JOptionPane.INFORMATION_MESSAGE);
            } else if (btnSimpan.getText()=="Update") {
                sql="UPDATE tblbarang SET jenis=?, nama=?, tahun=?, bagian=?, seksi=?, ruang=?, kondisi=?, keterangan=? WHERE nomor='"+ nomor +"'";
                //Statement st=cn.createStatement();
                PreparedStatement st=(PreparedStatement) cn.prepareStatement(sql);
                try {
                    st.setString(1, cbojenis.getSelectedItem().toString());
                    st.setString(2, TxtNama.getText());
                    st.setString(3, TxtTahun.getText());
                    st.setString(4, cboBagian.getSelectedItem().toString());
                    st.setString(5, cboSeksi.getSelectedItem().toString());
                    st.setString(6, cboRuang.getSelectedItem().toString());
                    st.setString(7, cbokondisi.getSelectedItem().toString());
                    st.setString(8, TxtKeterangan.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Berhasil di Update","UPDATE",JOptionPane.INFORMATION_MESSAGE);

                }catch(SQLException se) {
                    JOptionPane.showMessageDialog(null,"Ada Kesalahan Dalam Update Data"+se,"Error",JOptionPane.YES_OPTION);
                }
            }
            BersihText();
            aktifText(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Ada Kesalahan dalam Menyimpan Data Pada :"+e,"Error",JOptionPane.INFORMATION_MESSAGE);
        }
                loadData();
    }//GEN-LAST:event_btnSimpanActionPerformed
    }
    
    private void TxtNomorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomorKeyTyped

    }//GEN-LAST:event_TxtNomorKeyTyped

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String nomor=TxtNomor.getText();
        String nama=TxtNama.getText();
        String keterangan =TxtKeterangan.getText();
    if ((nomor.isEmpty()) | (nama.isEmpty())| (keterangan.isEmpty()))
       {JOptionPane.showMessageDialog(null,"Data Masih Ada Kosong, Silahkan Cek Kembali. ");
        TxtNomor.requestFocus();
    }
else{
        int tanya=JOptionPane.showConfirmDialog(null,"Yakin No. Inventaris : "+ TxtNomor.getText()+"Akan Dihapus?","Hapus",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (tanya==0)

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");
                String sql= "DELETE FROM tblbarang WHERE nomor='"+TxtNomor.getText()+"'";
                Statement st=cn.createStatement();
                st. executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Hapus Data Berhasil...","Sukses",JOptionPane.INFORMATION_MESSAGE);
                BersihText();
                aktifText(false);
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan dalam Menyimpan Data Pada :"+e,"Error",JOptionPane.INFORMATION_MESSAGE);
            }
                finally{
            loadData();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        BersihText();
        aktifText(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void TxtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKeteranganActionPerformed


    private void TxtNomorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomorKeyReleased
            if (TxtNomor.getText()==""){
                JOptionPane.showMessageDialog(null,"No. Inventaris Belum Anda Masukkan");
            }else {
                String nomor=TxtNomor.getText();
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");
                    String sql = "SELECT * FROM tblbarang WHERE nomor='"+nomor+"'";
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()){
                        JOptionPane.showMessageDialog(null,"No. Inventaris Sudah Anda Masukkan");
                        cbojenis.setSelectedItem(rs.getString("jenis"));
                        TxtNama.setText(rs.getString("nama"));
                        TxtTahun.setText(rs.getString("tahun"));
                        cboBagian.setSelectedItem(rs.getString("bagian"));
                        cboSeksi.setSelectedItem(rs.getString("seksi"));
                        cboRuang.setSelectedItem(rs.getString("ruang"));
                        cbokondisi.setSelectedItem(rs.getString("kondisi"));
                        TxtKeterangan.setText(rs.getString("keterangan"));
                        btnSimpan.setText("UPDATE");
                        btnSimpan.setMnemonic('U');
                        TxtNomor.setEnabled(false);
                        cbojenis.requestFocus();
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Ada Kesalahan dalam Menyimpan Data Pada"+e,"Error",JOptionPane.INFORMATION_MESSAGE);

                }

        }
    }//GEN-LAST:event_TxtNomorKeyReleased

    private void cboSeksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSeksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSeksiActionPerformed

    private void cbokondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbokondisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbokondisiActionPerformed

    private void cbojenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbojenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbojenisActionPerformed

    private void cbojenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbojenisItemStateChanged
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");
            Statement  st = cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String     SQL = "SELECT * FROM tbljenis where jenis= '"+ cbojenis.getSelectedItem().toString()+"'";
            ResultSet  rs = st.executeQuery(SQL);
            rs.absolute(1);
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_cbojenisItemStateChanged

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        new FrmJenisBaru().setVisible(true);
    }//GEN-LAST:event_btnCariActionPerformed

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaActionPerformed

    private void TxtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaKeyReleased

    private void TxtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaKeyTyped

    private void cboBagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBagianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboBagianActionPerformed

    private void cboRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRuangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRuangActionPerformed

    private void cboSeksiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSeksiItemStateChanged
       if ((cboBagian.getSelectedItem()=="Transaksi Energi Listrik") && (cboSeksi.getSelectedItem()=="Kosong")){
            cboRuang.removeAllItems();
            cboRuang.addItem("Asman TEL");
            cboRuang.addItem("Sekretaris Asman TEL");
            cboRuang.addItem("TERA");
            cboRuang.addItem("P2TL");
        }
        else if ((cboSeksi.getSelectedItem()=="Transaksi Energi Listrik")|(cboSeksi.getSelectedItem()== "Pengendalian Susut") | (cboSeksi.getSelectedItem()=="Pemeliharaan Meter")){
        cboRuang.removeAllItems();
        cboRuang.addItem("Transaksi Energi Listrik");
        cboRuang.addItem("Seksi TEL");
        cboRuang.addItem("Seksi HAR Meter");
        cboRuang.addItem("Seksi Proteksi");
        }
        else if ((cboBagian.getSelectedItem()=="Pelayanan & Adm") && (cboSeksi.getSelectedItem()== "Adm Umum")){
        cboRuang.removeAllItems();
        cboRuang.addItem("Keuangan");
        cboRuang.addItem("Akuntansi");
        cboRuang.addItem("Sekretariat Umum");
        cboRuang.addItem("Humas");
        cboRuang.addItem("Ruang Rapat");
        cboRuang.addItem("Operator Telepon");
        cboRuang.addItem("Kasir");
        cboRuang.addItem("Gudang LT.I");
        }
        else if ((cboBagian.getSelectedItem()=="Pelayanan & Adm") && (cboSeksi.getSelectedItem()=="Kosong")){
        cboRuang.removeAllItems();
        cboRuang.addItem("Asman PAD");
        cboRuang.addItem("PI");
        cboRuang.addItem("DCP-SP");
        cboRuang.addItem("Panitia Barang & Jasa");
        }
        else if ((cboSeksi.getSelectedItem()=="PPL")){
        cboRuang.removeAllItems();
        cboRuang.addItem("Penagihan");
        cboRuang.addItem("PPL");
        }

    }//GEN-LAST:event_cboSeksiItemStateChanged

    private void cboBagianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBagianItemStateChanged
    if (cboBagian.getSelectedItem()=="Jaringan") {
        cboSeksi.removeAllItems();
        cboRuang.removeAllItems();
        cboSeksi.addItem ("Operasi");
        cboSeksi.addItem("Pemeliharaan");
        cboSeksi.addItem("Kosong");
        cboRuang.addItem("Seksi Pemeliharaan Distribusi");
        cboRuang.addItem("Seksi Operasi Distribusi");
        cboRuang.addItem("Logistik");
    }
    else if (cboBagian.getSelectedItem()=="Transaksi Energi Listrik") {
        cboSeksi.removeAllItems();
        cboRuang.removeAllItems();
        cboSeksi.addItem ("Transaksi Energi Listrik");
        cboSeksi.addItem("Pengendalian Susut");
        cboSeksi.addItem("Pemeliharaan Meter");
        cboSeksi.addItem("Kosong");
    }
    else if (cboBagian.getSelectedItem()=="Pelayanan & Adm") {
        cboSeksi.removeAllItems();
        cboRuang.removeAllItems();
        cboSeksi.addItem ("PPL");
        cboSeksi.addItem("Adm Umum");
        cboSeksi.addItem("Kosong");


    }
    else if (cboBagian.getSelectedItem()=="Kosong") {
        cboSeksi.removeAllItems();
        cboRuang.removeAllItems();
        cboSeksi.addItem ("Kosong");
        cboRuang.addItem ("Manajer");
        cboRuang.addItem ("Sekretaris Manajer");
        cboRuang.addItem ("Ahli Kinerja");
        cboRuang.addItem ("SP");
        cboRuang.addItem ("P2BJ");
    }
    }//GEN-LAST:event_cboBagianItemStateChanged

    private void TxtTahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTahunKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_TxtTahunKeyTyped

    private void TxtTahunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTahunKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_TxtTahunKeyReleased

    private void TxtTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTahunActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TxtTahunActionPerformed

    private void cboRuangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRuangItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRuangItemStateChanged




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtKeterangan;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNomor;
    private javax.swing.JTextField TxtTahun;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cboBagian;
    private javax.swing.JComboBox cboRuang;
    private javax.swing.JComboBox cboSeksi;
    private javax.swing.JComboBox cbojenis;
    private javax.swing.JComboBox cbokondisi;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
