/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmNamaBaru.java
 *
 * Created on 20 Agu 14, 20:53:21
 */

package Forms;
import cls.ClassDB;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;

//import jie.koneksi.Koneksi;
/**
 *
 * @author Lidia Manik
 */
public class FrmJenisBaru extends javax.swing.JFrame {
    cls.ClassDB koneksi = new cls.ClassDB();
    Map<String, Object> param = new HashMap<String, Object>();
    private DefaultTableModel model;


    /** Creates new form FrmNamaBaru */
    public FrmJenisBaru() {
        initComponents();
        BersihText();
        aktifText(false);
        model=new DefaultTableModel();
        table.setModel(model);
        model.addColumn("Kode Investaris");
        model.addColumn("Nama Investaris");
        loadData();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
	Dimension frameSize = getSize();
	setLocation(
	(screenSize.width - frameSize.width) / 2,
	(screenSize.height - frameSize.height) / 2);
    }
     private Image oldIcon;

    protected static ImageIcon createImageIcon(String path) {

       // Ganti IconFrame dengan nama kelas jFrame Anda
        java.net.URL imgURL = FrmJenisBaru.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tbljenis";
            ResultSet r=s.executeQuery(sql);

            while (r.next()) {
                Object[] a=new Object[6];
                a[0]=r.getString("kode");
                a[1]=r.getString("jenis");
                model.addRow(a);
            }
            r.close();
            s.close();
            ShowData();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
    }

public void mouseClicked(MouseEvent e) {
      ShowData();
   }

public void ShowData() {

    int i=table.getSelectedRow();

        if(i==-1)
        {
            return;
        }
        String kode=(String) model.getValueAt(i, 0);
        TxtKode.setText(kode);
        String nama=(String) model.getValueAt(i, 1);
        TxtNama.setText(nama);

}


    private void aktifText(boolean param)
    {
        TxtKode.setEnabled(param);
        TxtNama.setEnabled(param);
        btnSimpan.setEnabled(param);
        btnHapus.setEnabled(param);
        btnBatal.setEnabled(param);
    }

    private void BersihText()
    {
        TxtKode.setText("");
        TxtNama.setText("");
        btnSimpan.setText("Simpan");
        btnSimpan.setMnemonic('S');
        btnTambah.setText("Tambah");
        btnTambah.setMnemonic('T');
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        TxtKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entri Jenis Inventaris");
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TxtNama.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });
        TxtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNamaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNamaKeyTyped(evt);
            }
        });

        table.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode Jenis", "Jenis Inventaris"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setRowSelectionAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel2.setText("Jenis Inventaris");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel11.setBackground(new java.awt.Color(255, 204, 51));
        jLabel11.setFont(new java.awt.Font("Eurostile", 0, 30));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Entri Jenis Inventaris");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        btnKeluar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Exit.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Refresh-32.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Trash.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/OK.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/New.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnKeluar)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TxtKode.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodeActionPerformed(evt);
            }
        });
        TxtKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtKodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtKodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtKodeKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel3.setText("Kode Inventaris");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(TxtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TxtNamaActionPerformed

    private void TxtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyReleased

}//GEN-LAST:event_TxtNamaKeyReleased

    private void TxtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyTyped

}//GEN-LAST:event_TxtNamaKeyTyped

    private void tabletblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletblBarangMouseClicked
        ShowData();
}//GEN-LAST:event_tabletblBarangMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        this.dispose();
}//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        BersihText();
        aktifText(false);
}//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       String kode=TxtKode.getText();
       String jenis=TxtNama.getText();

        if (jenis.isEmpty()|kode.isEmpty())
       {
           JOptionPane.showMessageDialog(null,"Anda belum menentukan pilihan.");
       }
        else{
        int tanya=JOptionPane.showConfirmDialog(null,"Yakin Jenis Inventaris : "+ TxtNama.getText()+" Akan Dihapus?","Hapus",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (tanya==0)

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");
                String sql="DELETE FROM tbljenis WHERE jenis='"+TxtNama.getText()+"'";
                Statement st=cn.createStatement();
                st. executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Hapus Data Berhasil...","Sukses",JOptionPane.INFORMATION_MESSAGE);
                BersihText();
                aktifText(false);
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Ada Kesalahan dalam Menyimpan Data Pada :"+e,"Error",JOptionPane.INFORMATION_MESSAGE);
            } finally{
                loadData();
            }
        }
}//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String kode="",jenis="",sql="";
        try{
       kode=TxtKode.getText();
       jenis=TxtNama.getText();
       if (jenis.isEmpty()|kode.isEmpty())
       {
           JOptionPane.showMessageDialog(null,"Data Masih Ada Yang Kosong, Silahkan Dilengkapi");
           TxtKode.requestFocus();
       }
        else{

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");
            if (btnSimpan.getText()=="Simpan") {
                //Mengambil data yg dimasukkan dari JTextField
                sql="Insert into tbljenis values('"+kode+"','"+jenis+"')";
                Statement st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Sudah Disimpan","Simpan",JOptionPane.INFORMATION_MESSAGE);
            } else if (btnSimpan.getText()=="Update") {
                sql="UPDATE tbljenis SET jenis=?  WHERE kode='"+ kode +"'";
                //Statement st=cn.createStatement();
                PreparedStatement st=(PreparedStatement) cn.prepareStatement(sql);
                try {
                    st.setString(1, TxtNama.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Berhasil di Update","Update",JOptionPane.INFORMATION_MESSAGE);
}catch(SQLException se) {
                    JOptionPane.showMessageDialog(null,"Ada Kesalahan Dalam Update Data"+se,"Error",JOptionPane.YES_OPTION);
                }
            }
            BersihText();
            aktifText(false);
    }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Ada Kesalahan dalam Menyimpan Data Pada :"+e,"Error",JOptionPane.INFORMATION_MESSAGE);
        }
        loadData();
}//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (btnTambah.getText()=="Tambah") {
            aktifText(true);
            this.TxtKode.requestFocusInWindow();

        } else if (btnTambah.getText()=="Edit") {
            btnTambah.setText("Edit");
            btnSimpan.setText("Update");
            btnSimpan.setMnemonic('U');
            aktifText(true);
            TxtNama.setEnabled(true);
        }
}//GEN-LAST:event_btnTambahActionPerformed

    private void TxtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNamaKeyPressed

    }//GEN-LAST:event_TxtNamaKeyPressed

    private void TxtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodeActionPerformed

    private void TxtKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeKeyPressed

    }//GEN-LAST:event_TxtKodeKeyPressed

    private void TxtKodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeKeyReleased
            if (TxtKode.getText()==""){
                JOptionPane.showMessageDialog(null,"No. Jenis Inventaris Belum Anda Masukkan");
            }else {
                String kode=TxtKode.getText();
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");
                    String sql = "SELECT*FROM tbljenis WHERE kode='"+kode+"'";
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()){
                        JOptionPane.showMessageDialog(null,"No. Inventaris Sudah Anda Masukkan");
                        TxtNama.setText(rs.getString("jenis"));
                        btnSimpan.setText("Update");
                        btnSimpan.setMnemonic('U');
                        TxtKode.setEnabled(false);
                        TxtNama.requestFocus();
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Ada Kesalahan dalam Menyimpan Data Pada"+e,"Error",JOptionPane.INFORMATION_MESSAGE);

                }

        }
    }//GEN-LAST:event_TxtKodeKeyReleased

    private void TxtKodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodeKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
                        //untuk ganti icon
        oldIcon = getIconImage();
ImageIcon newIcon = createImageIcon("icon_file.png");
setIconImage(newIcon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJenisBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtKode;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
