/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLogin.java
 *
 * Created on 15 Agu 14, 22:16:36
 */

package Forms;
import cls.ClassDB;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Lidia Manik
 */
public class FrmLogin extends javax.swing.JFrame {
    public Connection Con;
    public ResultSet RsUser;
    public Statement st;
    public Statement st2;
    public MenuAdminAktif MenuAdminAktif;
    private Image oldIcon;
    /** Creates new form FrmLogin */

    
    public FrmLogin() {
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pln","root","root");
        st=Con.createStatement();
        st2=Con.createStatement();

         } catch(Exception e){
    }
    setTanggal();
    //pemanggilan dari method method
    setJam();

    //tampilan tengah
    	Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
	Dimension frameSize = getSize();
	setLocation(
	(screenSize.width - frameSize.width) / 2,
	(screenSize.height - frameSize.height) / 2);
	}
  


    protected static ImageIcon createImageIcon(String path) {

       // Ganti IconFrame dengan nama kelas jFrame Anda
        java.net.URL imgURL = MenuTamu.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }


//untuk perintah penampilan tanggal
public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd MMMM yyyy");
    lblTanggal.setText(kal.format(skrg));
    }


//untuk perintah penampilan tanggal
public void setJam(){
ActionListener taskPerformer = new ActionListener() {

public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String waktu = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

lblJam.setText(waktu+":"+menit+":"+detik+"");
}
};
new Timer(1000, taskPerformer).start();
}




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLog_In = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuBeranda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuFile = new javax.swing.JMenu();
        MenuLaporan = new javax.swing.JMenu();
        MenuInformasi = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/masuk1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel3.setText("Username");

        txtUser_Name.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        txtUser_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser_NameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jLabel5.setText("Password");

        txtPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        btnLog_In.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14));
        btnLog_In.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.png"))); // NOI18N
        btnLog_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLog_InMouseClicked(evt);
            }
        });
        btnLog_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog_InActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI Light", 1, 15));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        lblTanggal.setText("Tanggal");

        lblJam.setText("Jam");

        MenuBeranda.setBackground(new java.awt.Color(255, 255, 255));
        MenuBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/Home.png"))); // NOI18N
        MenuBeranda.setText("Beranda   ");
        MenuBeranda.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuBeranda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                MenuBerandaMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        MenuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBerandaActionPerformed(evt);
            }
        });

        jMenuItem1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jMenuItem1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/merah.png"))); // NOI18N
        jMenuItem1.setText("Log In");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuBeranda.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        jMenuItem2.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hijau.png"))); // NOI18N
        jMenuItem2.setText("Log Out");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        MenuBeranda.add(jMenuItem2);

        menuBar.add(MenuBeranda);

        MenuFile.setForeground(new java.awt.Color(204, 204, 204));
        MenuFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add-32.png"))); // NOI18N
        MenuFile.setText("File    ");
        MenuFile.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFileMouseClicked(evt);
            }
        });
        MenuFile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                MenuFileComponentHidden(evt);
            }
        });
        MenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileActionPerformed(evt);
            }
        });
        menuBar.add(MenuFile);

        MenuLaporan.setForeground(new java.awt.Color(204, 204, 204));
        MenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit-32.png"))); // NOI18N
        MenuLaporan.setText(" Laporan   ");
        MenuLaporan.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        menuBar.add(MenuLaporan);

        MenuInformasi.setForeground(new java.awt.Color(204, 204, 204));
        MenuInformasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        MenuInformasi.setText("Informasi   ");
        MenuInformasi.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInformasiActionPerformed(evt);
            }
        });
        menuBar.add(MenuInformasi);

        jMenu1.setForeground(new java.awt.Color(204, 204, 204));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3d bar chart.png"))); // NOI18N
        jMenu1.setText("Riwayat Pengguna   ");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        menuBar.add(jMenu1);

        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Exit.png"))); // NOI18N
        MenuExit.setText("Keluar");
        MenuExit.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuExitMouseClicked(evt);
            }
        });
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        menuBar.add(MenuExit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJam)
                    .addComponent(lblTanggal))
                .addContainerGap(657, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addGap(5, 5, 5))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txtUser_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnLog_In, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addGap(17, 17, 17)))
                .addGap(195, 195, 195))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblTanggal)
                .addGap(9, 9, 9)
                .addComponent(lblJam)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLog_In, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
}//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
}//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuBerandaMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MenuBerandaMenuDeselected
        // TODO add your handling code here:
}//GEN-LAST:event_MenuBerandaMenuDeselected

    private void MenuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBerandaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_MenuBerandaActionPerformed

    private void MenuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFileMouseClicked
}//GEN-LAST:event_MenuFileMouseClicked

    private void MenuFileComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MenuFileComponentHidden
        // TODO add your handling code here:
}//GEN-LAST:event_MenuFileComponentHidden

    private void MenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_MenuFileActionPerformed

    private void MenuInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInformasiActionPerformed

}//GEN-LAST:event_MenuInformasiActionPerformed

    private void MenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuExitMouseClicked

}//GEN-LAST:event_MenuExitMouseClicked

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuUtama.setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuExitActionPerformed

    private void txtUser_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser_NameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtUser_NameActionPerformed

private void simpantanggal(){
    String username=this.txtUser_Name.getText();
    String tanggal=this.lblTanggal.getText();
    String jam=this.lblJam.getText();
        try {
            Connection c=ClassDB.getkoneksi();
            String sql = "Insert into tblhistory values (?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, username);
            p.setString(2, tanggal);
            p.setString(3, jam);
            p.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Anda Tidak Tersimpan Dalam History");
        }
    }

private void usahalogin(){
            String password="", username="", tanggal="";
        try{
            password= txtPassword.getText();
            username=txtUser_Name.getText();
            tanggal=lblTanggal.getText();
            Class.forName("com.mysql.jdbc.Driver");
            String SQL = "select * from login where username = '"+txtUser_Name.getText()+"'" + " and password='" + String.valueOf(txtPassword.getPassword()) +"'";
            st=Con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            if (rs.next()){
            JOptionPane.showMessageDialog(null,"Login Berhasil");
                this.setVisible(false);
                MenuAdminAktif=new MenuAdminAktif();
                MenuAdminAktif.setVisible(true);
                MenuAdminAktif.show();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, User Name dan Password Invalid");
            }
        } catch(Exception e){

        }
}
    private void btnLog_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog_InActionPerformed
simpantanggal();
usahalogin();
}//GEN-LAST:event_btnLog_InActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuUtama.setVisible(true);
        this.dispose();
}//GEN-LAST:event_btnExitActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuUtama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void btnLog_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLog_InMouseClicked

    }//GEN-LAST:event_btnLog_InMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        oldIcon = getIconImage();
        ImageIcon newIcon = createImageIcon("icon_login.png");
        setIconImage(newIcon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLogin FrmLogin=new FrmLogin();
                FrmLogin.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBeranda;
    private javax.swing.JMenu MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuInformasi;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLog_In;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser_Name;
    // End of variables declaration//GEN-END:variables




}
