/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLaporan.java
 *
 * Created on 20 Agu 14, 22:10:51
 */

package Forms;
import cls.ClassDB;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;



/**
 *
 * @author Lidia Manik
 */

public class FrmLaporan extends javax.swing.JInternalFrame {
        public FrmLaporan(String kriteria) {
        super("Laporan Inventaris",true,true,true,true);
        initComponents();
        String filename="";
        if (kriteria.trim().equals("")){
            filename="src/Laporan/inventaris.jasper";
        } else {
            filename="src/Laporan/inventaris_periode.jasper";
        }

        //2
        HashMap param = new HashMap();
        if(!kriteria.trim().equals("")) param.put("pTahun",kriteria);

        //3
        Connection cn= new ClassDB().getkoneksi();

            try{
            //4
            JasperPrint cetak =JasperFillManager.fillReport(filename, param, cn);
            JRViewer viewer = new JRViewer(cetak);
            getContentPane().add(viewer);
            viewer.setBounds(10,10,1354, 675);
            setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Maaf, Data Tidak Dapat Dicetak : "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }

    }



    /** Creates new form FrmLaporan */


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
