/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuUtama.java
 *
 * Created on 03 Des 11, 13:03:37
 */
package Forms;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author bagong
 */
public class MenuTamu extends javax.swing.JFrame {
    /** Creates new form MenuUtama */
    public MenuTamu() {
        initComponents();
        
    }
     private Image oldIcon;

    protected static ImageIcon createImageIcon(String path) {

       // Ganti IconFrame dengan nama kelas jFrame Anda
        java.net.URL imgURL = MenuTamu.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuBeranda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuFile = new javax.swing.JMenu();
        MenuLaporan = new javax.swing.JMenu();
        MenuInformasi = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Tamu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        menuBar.setFont(new java.awt.Font("Segoe UI Light", 0, 14));

        MenuBeranda.setBackground(new java.awt.Color(255, 255, 255));
        MenuBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/Home.png"))); // NOI18N
        MenuBeranda.setText("Beranda   ");
        MenuBeranda.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBerandaMouseClicked(evt);
            }
        });
        MenuBeranda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                MenuBerandaMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        MenuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBerandaActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/merah.png"))); // NOI18N
        jMenuItem1.setText("Log In");
        MenuBeranda.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hijau.png"))); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed1(evt);
            }
        });
        MenuBeranda.add(jMenuItem2);

        menuBar.add(MenuBeranda);

        MenuFile.setForeground(new java.awt.Color(204, 204, 204));
        MenuFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add-32.png"))); // NOI18N
        MenuFile.setText("File    ");
        MenuFile.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFileMouseClicked(evt);
            }
        });
        MenuFile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                MenuFileComponentHidden(evt);
            }
        });
        MenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileActionPerformed(evt);
            }
        });
        menuBar.add(MenuFile);

        MenuLaporan.setBackground(new java.awt.Color(204, 204, 204));
        MenuLaporan.setForeground(new java.awt.Color(204, 204, 204));
        MenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit-32.png"))); // NOI18N
        MenuLaporan.setText(" Laporan   ");
        MenuLaporan.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        menuBar.add(MenuLaporan);

        MenuInformasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        MenuInformasi.setText("Informasi   ");
        MenuInformasi.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuInformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuInformasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuInformasiMouseEntered(evt);
            }
        });
        MenuInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInformasiActionPerformed(evt);
            }
        });
        menuBar.add(MenuInformasi);

        jMenu1.setForeground(new java.awt.Color(204, 204, 204));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3d bar chart.png"))); // NOI18N
        jMenu1.setText("Riwayat Pengguna   ");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        menuBar.add(jMenu1);

        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Exit.png"))); // NOI18N
        MenuExit.setText("Keluar");
        MenuExit.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuExitMouseClicked(evt);
            }
        });
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        menuBar.add(MenuExit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1313, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1329)/2, (screenSize.height-700)/2, 1329, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
       
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15ActionPerformed

    private void MenuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBerandaActionPerformed
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuUtama.setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuBerandaActionPerformed

    private void MenuFileComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MenuFileComponentHidden
        // TODO add your handling code here:
}//GEN-LAST:event_MenuFileComponentHidden

    private void MenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_MenuFileActionPerformed

    private void MenuInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInformasiActionPerformed

}//GEN-LAST:event_MenuInformasiActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed

}//GEN-LAST:event_MenuExitActionPerformed

    private void MenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuExitMouseClicked
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuUtama.setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuExitMouseClicked

    private void MenuBerandaMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MenuBerandaMenuDeselected
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBerandaMenuDeselected

    private void MenuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFileMouseClicked

    }//GEN-LAST:event_MenuFileMouseClicked

    private void MenuBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBerandaMouseClicked

    }//GEN-LAST:event_MenuBerandaMouseClicked

    private void MenuInformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInformasiMouseClicked
        FrmPencarian1 s=new FrmPencarian1();
        jDesktopPane1.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_MenuInformasiMouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuUtama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuUtama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuInformasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInformasiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuInformasiMouseEntered

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
                //untuk ganti icon
        oldIcon = getIconImage();
ImageIcon newIcon = createImageIcon("icon_guest.png");
setIconImage(newIcon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem2ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MenuTamu MenuTamu=new MenuTamu();
                MenuTamu.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBeranda;
    private javax.swing.JMenu MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuInformasi;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
