/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuUtama.java
 *
 * Created on 03 Des 11, 13:03:37
 */
package Forms;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.awt.Toolkit;

/**
 *
 * @author bagong
 */
public class MenuUtama extends javax.swing.JFrame {
    /** Creates new form MenuUtama */
    public MenuUtama() {
        initComponents();

        //tampilan tengah
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
	Dimension frameSize = getSize();
	setLocation(
	(screenSize.width - frameSize.width) / 2,
	(screenSize.height - frameSize.height) / 2);

    }
            private Image oldIcon;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuBeranda = new javax.swing.JMenu();
        MenuAdmin = new javax.swing.JMenuItem();
        MenuPengunjung = new javax.swing.JMenuItem();
        MenuFile = new javax.swing.JMenu();
        MenuLaporan = new javax.swing.JMenu();
        MenuInformasi = new javax.swing.JMenu();
        MenuRiwayat = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Inventaris PT. PLN Persero");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        label3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        label3.setText("Aplikasi Inventaris");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pln.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("PT. PLN PERSERO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        MenuBeranda.setBackground(new java.awt.Color(255, 255, 255));
        MenuBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/Home.png"))); // NOI18N
        MenuBeranda.setText("Beranda   ");
        MenuBeranda.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuBeranda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                MenuBerandaMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        MenuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBerandaActionPerformed(evt);
            }
        });

        MenuAdmin.setBackground(new java.awt.Color(51, 51, 51));
        MenuAdmin.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        MenuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/administrator.png"))); // NOI18N
        MenuAdmin.setText("Admin");
        MenuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdminMouseClicked(evt);
            }
        });
        MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminActionPerformed(evt);
            }
        });
        MenuBeranda.add(MenuAdmin);

        MenuPengunjung.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        MenuPengunjung.setForeground(new java.awt.Color(51, 51, 51));
        MenuPengunjung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pelanggan.png"))); // NOI18N
        MenuPengunjung.setText("Tamu");
        MenuPengunjung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPengunjungMouseClicked(evt);
            }
        });
        MenuPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPengunjungActionPerformed(evt);
            }
        });
        MenuBeranda.add(MenuPengunjung);

        menuBar.add(MenuBeranda);

        MenuFile.setForeground(new java.awt.Color(204, 204, 204));
        MenuFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add-32.png"))); // NOI18N
        MenuFile.setText("File    ");
        MenuFile.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuFile.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFileMouseClicked(evt);
            }
        });
        MenuFile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                MenuFileComponentHidden(evt);
            }
        });
        MenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileActionPerformed(evt);
            }
        });
        menuBar.add(MenuFile);

        MenuLaporan.setForeground(new java.awt.Color(204, 204, 204));
        MenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit-32.png"))); // NOI18N
        MenuLaporan.setText(" Laporan   ");
        MenuLaporan.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        menuBar.add(MenuLaporan);

        MenuInformasi.setForeground(new java.awt.Color(204, 204, 204));
        MenuInformasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        MenuInformasi.setText("Informasi   ");
        MenuInformasi.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInformasiActionPerformed(evt);
            }
        });
        menuBar.add(MenuInformasi);

        MenuRiwayat.setForeground(new java.awt.Color(204, 204, 204));
        MenuRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3d bar chart.png"))); // NOI18N
        MenuRiwayat.setText("Riwayat Pengguna   ");
        MenuRiwayat.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        menuBar.add(MenuRiwayat);

        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Exit.png"))); // NOI18N
        MenuExit.setFont(new java.awt.Font("Segoe UI Light", 0, 14));
        MenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuExitMouseClicked(evt);
            }
        });
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        menuBar.add(MenuExit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1329)/2, (screenSize.height-694)/2, 1329, 694);
    }// </editor-fold>//GEN-END:initComponents

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
       
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15ActionPerformed

    private void MenuPengunjungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPengunjungMouseClicked
                MenuTamu MenuTamu=new MenuTamu();
                MenuTamu.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuTamu.setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuPengunjungMouseClicked

    private void MenuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdminMouseClicked
        new FrmLogin().setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuAdminMouseClicked

    private void MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminActionPerformed
        new FrmLogin().setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuAdminActionPerformed

    private void MenuBerandaMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MenuBerandaMenuDeselected
        // TODO add your handling code here:
}//GEN-LAST:event_MenuBerandaMenuDeselected

    private void MenuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBerandaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_MenuBerandaActionPerformed

    private void MenuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFileMouseClicked
        new FrmLogin().setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuFileMouseClicked

    private void MenuFileComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MenuFileComponentHidden
        // TODO add your handling code here:
}//GEN-LAST:event_MenuFileComponentHidden

    private void MenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_MenuFileActionPerformed

    private void MenuInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInformasiActionPerformed

}//GEN-LAST:event_MenuInformasiActionPerformed

    private void MenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuExitMouseClicked
        System.exit(0);
}//GEN-LAST:event_MenuExitMouseClicked

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        new MenuUtama().setVisible(true);
        this.dispose();
}//GEN-LAST:event_MenuExitActionPerformed

    private void MenuPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPengunjungActionPerformed
                MenuTamu MenuTamu=new MenuTamu();
                MenuTamu.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MenuTamu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPengunjungActionPerformed


    protected static ImageIcon createImageIcon(String path) {

       // Ganti IconFrame dengan nama kelas jFrame Anda
        java.net.URL imgURL = MenuUtama.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //untuk ganti icon
        oldIcon = getIconImage();
ImageIcon newIcon = createImageIcon("icon_home.png");
setIconImage(newIcon.getImage());

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MenuUtama MenuUtama=new MenuUtama();
                MenuUtama.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAdmin;
    private javax.swing.JMenu MenuBeranda;
    private javax.swing.JMenu MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuInformasi;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenuItem MenuPengunjung;
    private javax.swing.JMenu MenuRiwayat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables




}
